@startuml

!include "plantuml-toolset/super-serious-skin.iwsd"

skinparam State {
    BackgroundColor<<refunded>>  #ffd54f
    BackgroundColor<<cancelled>>  #e57373
    BackgroundColor<<fulfilled>>  #81c784
}

skinparam GenericArrowFontSize 11

state cancelled <<cancelled>>
state refunded <<refunded>>
state fulfilled <<fulfilled>>

cancelled : overdue
cancelled : user request
cancelled : invalid

[*] -r-> unpaid : <b>1</b> issue
unpaid -r-> cancelled : <b>2</b> cancel
unpaid --> paid : <b>3</b> pay

paid --> refunded : <b>4</b> refund
paid --> fulfilled : <b>5</b> fulfill

@enduml
